application:
  actions: actions
  web: web-src
  runtimeManifest:
    packages:
      gmr-api:
        license: Apache-2.0
        actions:
          generic:
            function: actions/generic/index.js
            web: 'yes'
            runtime: nodejs:22
            inputs:
              LOG_LEVEL: debug
            annotations:
              require-adobe-auth: true
              final: true
          publish-events:
            function: actions/publish-events/index.js
            web: 'yes'
            runtime: nodejs:22
            inputs:
              LOG_LEVEL: debug
              apiKey: $SERVICE_API_KEY
            annotations:
              require-adobe-auth: true
              final: true
          success-story:
            function: actions/success-story/index.js
            web: 'yes'
            runtime: nodejs:22
          news-update:
            function: actions/news-update/index.js
            web: 'yes'
            runtime: nodejs:22
          news-details:
            function: actions/news-details/index.js
            web: 'yes'
            runtime: nodejs:22
          algolia-indexer:
            function: actions/algolia-indexer/index.js
            web: 'yes'
            runtime: nodejs:22
          csv-to-cf:
            function: actions/csv-to-cf/index.js
            web: 'yes'
            runtime: nodejs:22
          news-pre:
            function: actions/news-pre/index.js
            web: 'yes'
            runtime: nodejs:22
          news-next:
            function: actions/news-next/index.js
            web: 'yes'
            runtime: nodejs:22
          recent-posts:
            function: actions/recent-posts/index.js
            web: 'yes'
            runtime: nodejs:22
        # triggers:
        #   daily-trigger:
        #     feed: /whisk.system/alarms/cron
        #     inputs:
        #       cron: "0 2 * * *"
        #       timezone: "Asia/Kolkata"